apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diabetes-care-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diabetes-care-service
            port:
              number: 80
